---
title: "Lab 4 Shiny Ineractive RMD"
author: "Anastasia Kunz"
date: "1/25/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```


```{r flippers, echo = FALSE}

inputPanel(
  
  selectInput(inputId = "pick_spp", 
              label = "Pick your penguin species:",
              choice = c("Adeliee" = "Adelie", "Chinstrappy" = "Chinstrap", "Gentoo"), #if you want it to show up differently than whats in the data, you can put what you want in quotes = what it is in quotes
              selected = "Gentoo" #default
              ), 
  
  sliderInput(inputId = "pt_slider",
              label = "Set your point size:",
              min = 1,
              max = 10,
              step = 0.5,
              value = 5)
  
) # END INPUT PANEL CODE: BEGIN OUTPUT

penguin_set <- reactive({
  penguins %>% 
    filter(species == input$pick_spp)
  
  
})

#output here

renderPlot({
  ggplot(data = penguin_set(), aes(x = flipper_length_mm, y = body_mass_g))+
    geom_point(size = input$pt_slider)
  
  
})

```




